services:
  app:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankiut
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./script/dumpSQL_JUnitTest.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
