name: SonarQube with Docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze with Docker
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      # Build and Run Docker Environment
      - name: Build and Start Docker Compose
        run: |
          cd _00_ASBank2023
          # Build and start the Docker containers
          docker-compose up -d --build

          # Wait for MySQL to be ready
          echo "Waiting for MySQL to be available..."
          until docker exec db mysql --user=root --password=root --execute="SELECT 1"; do
            sleep 5s
          done

          # Initialize the database
          docker exec -i db mysql --user=root --password=root --database=bankiut < ./_00_ASBank2023/init.sql

      # Run Maven Build and Sonar Analysis
      - name: Run Maven Build and SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Execute Maven build and analysis inside the Docker container
          docker exec app mvn -f ./_00_ASBank2023/pom.xml clean verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=JulienMaa_QualDev_G7

      # Clean Up Docker Environment
      - name: Tear Down Docker
        if: always()
        run: docker-compose down
